### ISSUE TITLE
`float` crashes on negative numbers

### ISSUE THREAD

**Issue by BrianHicks** [elm-tools/parser#2]
SSCCE:

```elm
Parser.run Parser.float "-1"
```

Output:

```
Error: Ran into a `Debug.crash` in module `Parser`

This was caused by the `case` expression between lines 695 and 707.
One of the branches ended with a crash and the following value got through:

    Err "could not convert string '' to a Float"

The message provided by the code author is:

    The `Parser.float` parser seems to have a bug.
Please report an SSCCE to <https://github.com/elm-tools/parser/issues>.
```

**Comment by evancz** [comment]
This had the same root cause as #1 so it should be solved by 490203d404baa2ceeb6b6dd06b4081ea7d87f2c4 as well. Thanks for the report!

**Comment by antoine-atmire** [comment]
```
> Parser.run Parser.float "1"
Ok 1 : Result.Result Parser.Error Float

> Parser.run Parser.float "-1"
Err { row = 1, col = 1, source = "-1", problem = BadFloat, context = [] }
    : Result.Result Parser.Error Float

> Parser.run Parser.float "-1.1"
Err { row = 1, col = 1, source = "-1.1", problem = BadFloat, context = [] }
    : Result.Result Parser.Error Float
```
Parsing negative numbers with `float` does not cause a crash anymore, but it is still not succeeding. Same for `int`. I notice there are no examples with negative numbers for these two parsers in the docs. Is this an oversight?

I've come up with this solution for the time being
```
float : Parser Float
float =
    Parser.succeed
        (\negative f ->
            if negative then
                -f
            else
                f
        )
        |= minusSign
        |= Parser.float


minusSign : Parser Bool
minusSign =
    Parser.succeed
        (List.head
            >> Maybe.map (\x -> True)
            >> Maybe.withDefault False
        )
        |= zeroOrMore (symbol "-")
```

**Comment by evancz** [comment]
Negative numbers are not handled by default. Issue #7 will address that by having a more customizable number parser.

You could also define `minusSign` like this:

```elm
minus : Parser Bool
minus =
  oneOf
    [ map (\_  -> True) (symbol "-")
    , succeed False
    ]
```
